package main

import (
	"fmt"
	"github.com/tidwall/gjson"
	//"html/template"
	"bytes"
	"io/ioutil"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", defaultHandler)
	http.HandleFunc("/showProductList", showProductListHandler)
	http.HandleFunc("/fillInTemplatePage", fillInTemplatePageHandler)
	err := http.ListenAndServe(":8080", nil)
	if err != nil {
		log.Fatal("ListenAndServe: ", err)
		return
	}
}

func fillInTemplatePageHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Println(r.Method)
	if r.Method == "POST" {
		r.ParseForm()
		//body, _ := ioutil.ReadAll(r.Body)
		fmt.Println(r.Form)
		fmt.Println("scheme", r.URL.Scheme)
		fmt.Println(r.Form["url_long"])
		if len(r.Form) > 0 {
			productId := r.Form["productChoice"][0]
			w.Header().Set("Content-Type", "text/html; charset=utf-8")
			fmt.Fprintf(w, buildTemplate(productId))
		}
	}
}

func buildTemplate(productId string) string {
	var bodyBuffer bytes.Buffer
	bodyBuffer.WriteString("Please fill out the fields below: \n\n")
	bodyBuffer.WriteString("<form action=\"processOrder\" method=\"post\">\n")
	data := getTemplateData(productId)
	templateList := gjson.Get(data, "results.data.templateFields.fieldlist.field")

	bodyBuffer.WriteString(data)

	fmt.Println("templateList:" + templateList.String())
	templateList.ForEach(func(key, value gjson.Result) bool {
		fieldName := value.Get("fieldname").String()
		required := value.Get("required").String() == "Y"
		//visible := value.Get("visible").String() == "Y"
		//fieldType := value.Get("type").String()
		//defaultValue := value.Get("default").String()
		//orgValue := value.Get("orgvalue").String()

		bodyBuffer.WriteString("Field: " + fieldName)
		bodyBuffer.WriteString("<input type=\"test\" name=\"" + fieldName + "\"")
		if required {
			bodyBuffer.WriteString(" required")
		}
		bodyBuffer.WriteString(">\n")

		bodyBuffer.WriteString("\n\n")
		return true
	})
	bodyBuffer.WriteString("<input type=\"submit\" value=\"Purchase\">")
	return bodyBuffer.String()
}

func getTemplateData(productId string) string {
	req, _ := http.NewRequest("GET", "https://testapi.pfl.com/products/"+productId+"?apikey=136085", nil)
	req.SetBasicAuth("miniproject", "Pr!nt123")
	req.Header.Set("Content-Type", "application/json")
	resp, _ := http.DefaultClient.Do(req)
	defer resp.Body.Close()
	fmt.Println("productIDHERe: " + productId)
	if resp.StatusCode == 200 {
		bodyBytes, _ := ioutil.ReadAll(resp.Body)
		body := string(bodyBytes)
		fmt.Println("here: body is : " + body)
		return body
	}
	return ""
}

func showProductListHandler(w http.ResponseWriter, r *http.Request) {
	req, _ := http.NewRequest("GET", "https://testapi.pfl.com/products?apikey=136085", nil)
	req.SetBasicAuth("miniproject", "Pr!nt123")
	req.Header.Set("Content-Type", "application/json")
	resp, _ := http.DefaultClient.Do(req)
	defer resp.Body.Close()
	if resp.StatusCode == 200 {
		bodyBytes, _ := ioutil.ReadAll(resp.Body)
		jsonString := string(bodyBytes)
		productList := gjson.Get(jsonString, "results.data")
		var bodyBuffer bytes.Buffer
		bodyBuffer.WriteString("<form action=\"/fillInTemplatePage\" method=\"post\" id=\"productSelection\">\n <input type=\"submit\">\n")
		bodyBuffer.WriteString("<select name=\"productChoice\">\n")

		productList.ForEach(func(key, value gjson.Result) bool {
			productName := value.Get("name")
			productId := value.Get("productID")
			bodyBuffer.WriteString("<option value=\"" + productId.String() + "\">" + productName.String() + "</option>\n")
			return true
		})

		bodyBuffer.WriteString("</select></form>")
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		fmt.Fprintf(w, bodyBuffer.String())
	}
}

//Would be better to have a way to ty the product ids right to the selection
// in case of matching names...
//func getProductIdFromName(fullSelection string, resultName string) int {
//	return gjson.Get(fullSelection, "results.data.#[name==\""+resultName+"\"].productId")
//}

func defaultHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Go web app test page 14423")
}

func testStuff() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	req, err := http.NewRequest("GET", "https://testapi.pfl.com/products?apikey=136085", nil)
	if err != nil {
		// handle err
	}
	req.SetBasicAuth("miniproject", "Pr!nt123")
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
	if resp.StatusCode == 200 {
		bodyBytes, _ := ioutil.ReadAll(resp.Body)
		bodyString := string(bodyBytes)
		//fmt.Println(bodyString)
		testValue := gjson.Get(bodyString, "results.data.#.name")
		fmt.Println("am here: ", testValue)

	}
}
