package main

import (
	"fmt"
	"github.com/tidwall/gjson"
	//"html/template"
	"bytes"
	"io/ioutil"
	"log"
	"net/http"
	"strings"
)

func main() {
	http.HandleFunc("/", defaultHandler)
	http.HandleFunc("/showProductList", showProductListHandler)
	http.HandleFunc("/fillInTemplatePage", fillInTemplatePageHandler)
	err := http.ListenAndServe(":8080", nil)
	if err != nil {
		log.Fatal("ListenAndServe: ", err)
		return
	}
}

func fillInTemplatePageHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Println(r.Method)
	if r.Method == "POST" {
		r.ParseForm()
		//body, _ := ioutil.ReadAll(r.Body)
		fmt.Println(r.Form)
		fmt.Println("scheme", r.URL.Scheme)
		fmt.Println(r.Form["url_long"])
		if len(Form) > 0 {
			productId := Form["productChoice"]
		}
	}
}

func showProductListHandler(w http.ResponseWriter, r *http.Request) {
	req, _ := http.NewRequest("GET", "https://testapi.pfl.com/products?apikey=136085", nil)
	req.SetBasicAuth("miniproject", "Pr!nt123")
	req.Header.Set("Content-Type", "application/json")
	resp, _ := http.DefaultClient.Do(req)
	defer resp.Body.Close()
	if resp.StatusCode == 200 {
		bodyBytes, _ := ioutil.ReadAll(resp.Body)
		jsonString := string(bodyBytes)
		productList := gjson.Get(jsonString, "results.data")
		var bodyBuffer bytes.Buffer
		bodyBuffer.WriteString("<form action=\"/fillInTemplatePage\" method=\"post\" id=\"productSelection\">\n <input type=\"submit\">\n")
		bodyBuffer.WriteString("<select name=\"productChoice\">\n")

		productList.ForEach(func(key, value gjson.Result) bool {
			productName := value.Get("name")
			productId := value.Get("productID")
			bodyBuffer.WriteString("<option value=\"" + productId.String() + "\">" + productName.String() + "</option>\n")
			return true
		})

		bodyBuffer.WriteString("</select></form>")
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		fmt.Fprintf(w, bodyBuffer.String())
	}
}

//Would be better to have a way to ty the product ids right to the selection
// in case of matching names...
//func getProductIdFromName(fullSelection string, resultName string) int {
//	return gjson.Get(fullSelection, "results.data.#[name==\""+resultName+"\"].productId")
//}

func defaultHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Go web app test page 14423")
}

func testStuff() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	req, err := http.NewRequest("GET", "https://testapi.pfl.com/products?apikey=136085", nil)
	if err != nil {
		// handle err
	}
	req.SetBasicAuth("miniproject", "Pr!nt123")
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
	if resp.StatusCode == 200 {
		bodyBytes, _ := ioutil.ReadAll(resp.Body)
		bodyString := string(bodyBytes)
		//fmt.Println(bodyString)
		testValue := gjson.Get(bodyString, "results.data.#.name")
		fmt.Println("am here: ", testValue)

	}
}
