package main

import (
	"fmt"
	"github.com/tidwall/gjson"
	"io/ioutil"
	"net/http"
)

func main() {
	testStuff()
}

func testStuff() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	req, err := http.NewRequest("GET", "https://testapi.pfl.com/products?apikey=136085", nil)
	if err != nil {
		// handle err
	}
	req.SetBasicAuth("miniproject", "Pr!nt123")
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
	if resp.StatusCode == 200 {
		bodyBytes, _ := ioutil.ReadAll(resp.Body)
		bodyString := string(bodyBytes)
		//fmt.Println(bodyString)
		testValue := gjson.Get(bodyString, "results.data.0.id")
		fmt.Println("am here: ", testValue)

	}
}
